# f5-hello-world - CI Build
# https://github.com/f5devcentral/f5-hello-world
# Artiom Lichtenstein
# v1.0.6, 31/12/2017

sudo: required

language: node_js
node_js:
  - "lts/*"

services:
  - docker

before_install:
  - docker pull f5devcentral/f5-hello-world
  - docker pull f5devcentral/f5-hello-world:ws 
  - docker run -dit -p 80:8080 -p 443:8443 f5devcentral/f5-hello-world
  - docker run -dit -p 4433:4433 f5devcentral/f5-hello-world:ws
  - docker ps -a

install:
  - npm install -g wscat3

script:
  - curl -s http://127.0.0.1/uri$(shuf -i 0-1313 -n 1)/index.php | grep 'Hello World'
  - curl -sk https://127.0.0.1/uri$(shuf -i 0-1313 -n 1)/secure/index.php -u user:user | grep 'Hello user'
  - echo 'hello_world' | wscat -s echo ws://127.0.0.1:4433 | grep 'hello_world'
